language: node_js
node_js:
   - "4.2"

branches:
  only:
    - master
    - dev
script:
  make riot

sudo: false

install:
  - npm i jade
  - npm i babel@5.8
  - npm i coffee-script
  - npm i livescript
  - npm i typescript-simple
  - npm i stylus
  - npm i nib
  - npm i node-sass
  - npm install

after_script:
  make test-sauce && make test-coveralls

notifications:
    email: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
